version: "5"

services:
  fastapi_app:
    build: .
    environment:
      - DOCKER=1
    env_file:
      - .docker.env
    command: >
      sh -c "uvicorn app.main:create_app --host 0.0.0.0"
    ports:
      - "8000:8000"

  db:
    image: postgres:15-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=calculation_db