version: "5"

services:

  fastapi_app:
    build: ./backend
    volumes:
      - .:/backend
    environment:
      - DOCKER=1
    env_file:
      - ./backend/.docker.env
    command: >
      sh -c "gunicorn src.main:create_app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8001"
    ports:
      - "8001:8001"
    expose:
      - 8001
    networks:
      - default
    depends_on:
      - db
      - mongodb


  celery:
    build: ./backend
    volumes:
      - .:/backend
    environment:
      - DOCKER=1
    env_file:
      - ./backend/.docker.env
    command: >
      sh -c "celery -A src.core.celery:app worker -l info"
    networks:
      - default
    depends_on:
      - fastapi_app
      - celery_beat
      - redis


  celery_beat:
    build: ./backend
    volumes:
      - .:/backend
    environment:
      - DOCKER=1
    env_file:
      - ./backend/.docker.env
    command: >
      sh -c "celery -A src.core.celery:app beat -l info"
    networks:
      - default
    depends_on:
      - fastapi_app
      - redis


  redis:
    image: redis:latest
    ports:
      - "6339:6339"
    expose:
      - 6339


  db:
    image: postgres:15-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=calculation_db
    networks:
      - default


  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8


  frontend:
     build: ./frontend
     ports:
       - "8888:8888"
     depends_on:
       fastapi_app:
         condition: service_started
     networks:
       - default

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - fastapi_app
    networks:
      - default



networks:
  default: {}
