version: "5"

services:
  fastapi_app:
    build: ./backend
    volumes:
      - .:/backend
    environment:
      - DOCKER=1
    env_file:
      - ./backend/.docker.env
    command: >
      sh -c "uvicorn src.main:create_app --host 0.0.0.0 --port 8001 --reload --factory"
    ports:
      - "8001:8001"

  db:
    image: postgres:15-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=calculation_db

  frontend:
     build: ./frontend
     ports:
       - "8888:8888"
     depends_on:
       fastapi_app:
         condition: service_started
